name: Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy to VPS using Appleboy SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e
            echo "🚀 Connected to VPS. Starting deployment..."

            # Ensure repository is up to date
            echo "📥 Pulling latest changes from main branch..."
            git pull origin main || { echo '❌ Git pull failed'; exit 1; }

            # Navigate to project directory
            cd /home/deploy_user/fastapi-book-project || { echo '❌ Failed to navigate'; exit 1; }

            # Ensure logs directory exists
            mkdir -p /home/deploy_user/fastapi-book-project/logs

            # Activate virtual environment and install dependencies
            source venv/bin/activate
            pip install -r requirements.txt || { echo '❌ Failed to install dependencies'; exit 1; }

            # Restart FastAPI service properly
            sudo systemctl restart fastapi || { echo '❌ Failed to restart FastAPI'; exit 1; }

            # Reload Nginx safely
            sudo systemctl reload nginx || { echo '❌ Failed to reload Nginx'; exit 1; }

            echo "✅ Deployment completed successfully!"

      - name: Notify Success
        if: success()
        run: echo "✅ Deployment succeeded!"

      - name: Notify Failure
        if: failure()
        run: echo "❌ Deployment failed! Check logs for details."
